
CREATE ROLE karm LOGIN
  -- PASSWORD 'karm'
  SUPERUSER INHERIT CREATEDB CREATEROLE NOREPLICATION;

CREATE DATABASE karm
  WITH OWNER = karm
       ENCODING = 'UTF8'
       TABLESPACE = pg_default
       LC_COLLATE = 'en_GB.UTF-8'
       LC_CTYPE = 'en_GB.UTF-8'
       CONNECTION LIMIT = -1
       TEMPLATE template0;
GRANT ALL ON DATABASE karm TO fc;
REVOKE ALL ON DATABASE karm FROM public;

